# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MageApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'ARCL'
  pod "ESTabBarController-swift"
  pod 'pop', '~> 1.0'
  pod 'lottie-ios'
  pod 'SDWebImage'
  pod 'ARSLineProgress'
  pod 'UIView-Shimmer', '~> 1.0'
  pod 'AnimatedCollectionViewLayout'
  pod 'TensorFlowLiteSwift'
  pod 'GoogleMaps'
  pod 'IQKeyboardManagerSwift'
end
